#!/bin/bash
eval "$(/opt/homebrew/bin/brew shellenv)"

# Homebrew bash-completion
if [ -f /opt/homebrew/etc/profile.d/bash_completion.sh ]; then
  source /opt/homebrew/etc/profile.d/bash_completion.sh
elif [ -f /usr/local/etc/profile.d/bash_completion.sh ]; then
  source /usr/local/etc/profile.d/bash_completion.sh
fi

if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

